apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo-$BRANCH_NAME
  name: mongo-$BRANCH_NAME
spec:
  #ports:
  #  - port: 27017
  #    targetPort: 27017
  type: NodePort
  ports:
    - port: 27017
  selector:
    name: mongo-$BRANCH_NAME
