apiVersion: v1
kind: Service
metadata:
  name: nodeapp-$BRANCH_NAME
  labels:
    name: nodeapp-$BRANCH_NAME
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    name: nodeapp-$BRANCH_NAME
